config/routes.rb
Rails.application.routes.draw do
  #mount Ckeditor::Engine => '/ckeditor'
  resources :lectures
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match 'home', :to => "static#index"
  root :to => "static#index"

  resources :lectures do 
    member do
      put "like", to: "lectures#upvote"
      put "dislike", to: "lectures#downvote"
      post "spam"  =>"lectures#spam"
    end
  end
  mount Commontator::Engine => '/commontator'
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :lectures
	belongs_to :user
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader
    belongs_to :user ,:optional => true
    belongs_to :course
    acts_as_votable
    acts_as_commontable
    has_and_belongs_to_many :users

    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :img, ImgUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_commontator

  has_and_belongs_to_many :lectures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            #devise_parameter_sanitizer.**permit**(:sign_up, keys: [:username])
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :is_female, :date_of_birth, :img) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :img) }
        end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base



  def create

    @course = Course.new(course_params)
    @course.user_id = current_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private

    def course_params
      params.require(:course).permit(:title, :user_id)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  def spam
    lecture = Lecture.find(params[:id])
    
     unless current_user.lectures.include?(lecture)
      current_user.lectures << lecture
     end
  end

  def index
    @lectures = Lecture.all
  end
  def upvote 
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    #redirect_to :back
    redirect_back fallback_location: root_path
  end  
  
  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_by current_user
    #redirect_to :back
    redirect_back fallback_location: root_path
  end

  private

    def lecture_params
      params.require(:lecture).permit(:content, :course_id, :attachment, :user_id)
    end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index 
        @lectures = Lecture.all     
        @courses = Course.all   
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/commontator/comments/_actions.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% can_edit = comment.can_be_edited_by?(user)
   can_delete = comment.can_be_deleted_by?(user) %>

<% if can_edit %>
  <%= link_to t('commontator.comment.actions.edit'),
              commontator.edit_comment_path(comment),
              id: "comment_#{comment.id.to_s}_edit_link",
              class: "comment_edit_link",
              remote: true %>
<% end %>

&nbsp;

<% if can_delete %>
  <% is_deleted = comment.is_deleted? %>
  <% del_string = is_deleted ? 'undelete' : 'delete' %>
  <%= link_to t("commontator.comment.actions.#{del_string}"),
              commontator.polymorphic_path([del_string, comment]),
              confirm: (!is_deleted ? t('commontator.comment.actions.confirm_delete') : nil),
              method: :put,
              id: "comment_#{comment.id.to_s}_#{del_string}_link",
              class: "comment_#{del_string}_link",
              remote: true %>
<% end %>

app/views/commontator/comments/_body.html.erb
<% # Clients of this partial must provide the following variable:
   # comment
%>

<%= simple_format comment.is_deleted? ? \
      t('commontator.comment.status.deleted_by',
        deleter_name: Commontator.commontator_name(comment.editor)) : \
      comment.body %>

app/views/commontator/comments/_form.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   #
   # Optionally, they can also supply the following variables:
   per_page ||= nil
   thread ||= nil
   no_remote ||= false
%>

<% config = comment.thread.config %>

<% if comment.errors.any? %>
  <div class="comment_error_explanation">
    <h3><%= t "commontator.comment.errors.#{comment.id.blank? ? 'create' : 'update'}" %></h3>

    <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([commontator, thread, comment],
             remote: !no_remote) do |f| %>

  <%= hidden_field_tag :per_page, per_page %>
  
  <div class="comment_form_field">
    <%= f.text_area :body, rows: '7' %>
    <%= javascript_tag('Commontator.initMentions()') if Commontator.mentions_enabled %>
  </div>
  
  <div class="comment_form_actions">
    <%= f.submit t("commontator.comment.actions.#{comment.id.blank? ? 'create' : 'update'}") %>
    <%= f.submit t('commontator.comment.actions.cancel'), name: 'cancel' %>
  </div>
  
<% end %>

app/views/commontator/comments/_list.html.erb
<% # Clients of this partial must supply the following variables:
   # comments
   # user
%>

<% comments.includes(:creator, :editor).each do |comment| %>
  <%= render partial: 'commontator/comments/show',
             locals: { comment: comment,
                          user: user } %>
<% end %>

app/views/commontator/comments/_show.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% creator = comment.creator
   name = Commontator.commontator_name(creator) || ''
   link = Commontator.commontator_link(creator, main_app) || ''
   avatar = Commontator.commontator_avatar(creator, self) || ''
%>

<div id="comment_<%= comment.id.to_s %>_div" class="comment">
  <div id="comment_<%= comment.id.to_s %>_top_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_commontator_span" class="comment_commontator">
      <%= link.blank? ? name : link_to(name, link) %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_actions_span" class="comment_actions">
      <%= render partial: 'commontator/comments/actions',
                 locals: { comment: comment,
                              user: user } %>
    </span>
  </div>
  <div id="comment_<%= comment.id.to_s %>_middle_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_avatar_span" class="comment_avatar">
      <%= avatar %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_votes_span" class="comment_votes">
      <%= render partial: 'commontator/comments/votes',
                 locals: { comment: comment,
                              user: user } %>
    </span>
    <div id="comment_<%= comment.id.to_s %>_body_div" class="comment_body">
      <%= render partial: 'commontator/comments/body',
                 locals: { comment: comment } %>
    </div>
  </div>
  <div id="comment_<%= comment.id.to_s %>_bottom_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_created_timestamp_span" class="comment_timestamp">
      <%= comment.created_timestamp %>
    </span>
    <br/>
    <span id="comment_<%= comment.id.to_s %>_updated_timestamp_span" class="comment_timestamp">
    <% if comment.is_modified? %>
      <%= comment.updated_timestamp %>
    <% end %>
    </span>
  </div>
</div>

app/views/commontator/comments/_votes.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   # user
%>

<% if comment.can_be_voted_on? %>
  <% can_vote = comment.can_be_voted_on_by?(user) %>
  <% vote = comment.get_vote_by(user) %>
  <% comment_voting = comment.thread.config.comment_voting.to_sym %>

  <% if comment_voting == :ld || comment_voting == :l %>
  <% vtype = (comment_voting == :ld) ? 'upvote' : 'like' %>
  <span id="comment_<%= comment.id %>_<%= vtype %>_span"
        class="comment_<%= vtype %>">
    <% if can_vote && (vote.blank? || !vote.vote_flag) %>
      <%= form_tag commontator.upvote_comment_path(comment),
            method: :put,
            remote: true do %>
        <%= image_submit_tag "commontator/upvote.png",
              onmouseover: "this.src='#{image_path("commontator/upvote_hover.png")}'",
              onmouseout: "this.src='#{image_path("commontator/upvote.png")}'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            method: :put,
            remote: true do %>
        <%= image_submit_tag "commontator/upvote_active.png",
              onmouseover: "this.src='#{image_path("commontator/upvote.png")}'",
              onmouseout: "this.src='#{image_path("commontator/upvote_active.png")}'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/upvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>

  <span id="comment_<%= comment.id %>_vote_count_span" class="comment_vote_count">
    <% config = comment.thread.config %>
    <%= config.vote_count_proc.call(comment.thread,
          comment.get_upvotes.size, comment.get_downvotes.size) %>
  </span>

  <% if comment_voting == :ld %>
  <span id="comment_<%= comment.id %>_downvote_span" class="comment_downvote">
    <% if can_vote && (vote.blank? || vote.vote_flag) %>
      <%= form_tag commontator.downvote_comment_path(comment),
            method: :put,
            remote: true do %>
        <%= image_submit_tag "commontator/downvote.png",
              onmouseover: "this.src='#{image_path("commontator/downvote_hover.png")}'",
              onmouseout: "this.src='#{image_path("commontator/downvote.png")}'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            method: :put,
            remote: true do %>
        <%= image_submit_tag "commontator/downvote_active.png",
              onmouseover: "this.src='#{image_path("commontator/downvote.png")}'",
              onmouseout: "this.src='#{image_path("commontator/downvote_active.png")}'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/downvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>
<% end %>

app/views/commontator/comments/cancel.js.erb
<% unless @comment.try(:id).blank? %>
  <% @comment.reload %>
  $("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
    render partial: 'body', locals: { comment: @comment }) %>");
<% end %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render partial: 'form',
           locals: { comment: @new_comment,
                        thread: @thread,
                        per_page: @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

<%= javascript_proc %>

app/views/commontator/comments/create.js.erb
<%= render partial: 'commontator/threads/show',
           locals: { thread: @thread,
                        user: @user,
                        page: @thread.new_comment_page(@per_page),
                        per_page: @per_page } %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render partial: 'form',
           locals: { comment: @new_comment,
                        thread: @thread,
                        per_page: @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

$("#comment_<%= @comment.id.to_s %>_div").hide().fadeIn()[0].scrollIntoView();

<%= javascript_proc %>

app/views/commontator/comments/delete.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render partial: 'body', locals: { comment: @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");
                                                           
$("#comment_<%= @comment.id.to_s %>_actions_span").html("<%= escape_javascript(
  render partial: 'actions',
         locals: { comment: @comment,
                      user: @user }) %>");
         
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render partial: 'votes',
         locals: { comment: @comment,
                      user: @user }) %>");

<%= javascript_proc %>

app/views/commontator/comments/edit.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render partial: 'form',
         locals: { comment: @comment }) %>");
         
<%= javascript_proc %>

app/views/commontator/comments/new.js.erb
$("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
  render partial: 'form',
         locals: { comment: @comment,
                      thread: @thread,
                      per_page: @per_page }) %>");

$("#thread_<%= @thread.id %>_new_comment_form_div").fadeIn()[0].scrollIntoView();

$("#thread_<%= @thread.id %>_new_comment_link_div").hide();

<%= javascript_proc %>

app/views/commontator/comments/update.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render partial: 'body', locals: { comment: @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");

<%= javascript_proc %>

app/views/commontator/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render partial: 'votes',
         locals: { comment: @comment,
                      user: @user }) %>");

<%= javascript_proc %>

app/views/commontator/shared/_thread.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% if thread.can_be_read_by?(user) %>
  <div id="thread_<%= thread.id %>_div" class="thread" style="display: none;">
    <% if @commontator_thread_show %>
      <%= render partial: 'commontator/threads/show',
                 locals: { thread: thread,
                              user: user,
                              page: @commontator_page,
                              per_page: @commontator_per_page } %>
    <% else %>
      <% subscription = thread.subscription_for(user) %>
      <%= link_to "#{t 'commontator.thread.actions.show'} (#{(subscription.unread_comments.count.to_s + '/') if subscription}#{thread.filtered_comments.count.to_s})",
                  commontator.thread_path(thread),
                  remote: true %>
    <% end %>
  </div>
<% end %>

app/views/commontator/subscriptions/_link.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% is_subscribed = !!thread.subscription_for(user) %>
<% sub_string = is_subscribed ? "unsubscribe" : "subscribe" %>
<%= link_to t("commontator.subscription.actions.#{sub_string}"),
            commontator.polymorphic_path([sub_string, thread]),
            confirm: (is_subscribed ? t('commontator.subscription.actions.confirm_unsubscribe') : \
                          nil),
            method: :put,
            id: "thread_#{thread.id.to_s}_#{sub_string}_link",
            class: "thread_#{sub_string}_link",
            remote: true %>

app/views/commontator/subscriptions/subscribe.js.erb
$("#thread_<%= @thread.id.to_s %>_subscription_span").html("<%= escape_javascript(
  render partial: 'link',
         locals: { thread: @thread,
                      user: @user }) %>");

<%= javascript_proc %>

app/views/commontator/threads/_hide_show_links.js.erb
<% # Clients of this partial must supply the following variables:
   # thread
%>

$("#thread_<%= thread.id %>_hide_link").click(function() {
  $("#thread_<%= thread.id %>_span").hide();

  $("#thread_<%= thread.id %>_show_span").fadeIn()[0].scrollIntoView();
});

$("#thread_<%= thread.id %>_show_link").click(function() {
  $("#thread_<%= thread.id %>_span").fadeIn()[0].scrollIntoView();

  $("#thread_<%= thread.id %>_show_span").hide();
});

$("#thread_<%= thread.id %>_hide_span").show();

app/views/commontator/threads/_reply.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
   # per_page

   hidden_class = @new_comment.nil? ? ' commontator_hidden' : '' %>

<div id="thread_<%= thread.id %>_reply" class="thread_reply">
  <% if thread.is_closed? %>
    <p><%= t 'commontator.thread.status.cannot_post' %></p>
  <% elsif !user %>
    <p><%= t 'commontator.require_login' %>.</p>
  <% else %>
    <div id="thread_<%= thread.id %>_new_comment_form_div" class="thread_new_comment_form<%=
    hidden_class %>">
      <% unless @new_comment.nil? %>
        <%= render partial: 'commontator/comments/form',
                   locals: { comment: @new_comment,
                                thread: thread,
                                per_page: per_page } %>
      <% end %>
    </div>

    <% if @new_comment.nil? %>
      <div id="thread_<%= thread.id %>_new_comment_link_div" class="thread_new_comment_link">
        <%= link_to t('commontator.comment.actions.new'),
            commontator.new_thread_comment_path(thread, per_page: per_page),
            remote: true %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/commontator/threads/_show.js.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
   # page
   # per_page
   # Optionally, they can also supply the following variable:
   show_all ||= false
%>

$("#thread_<%= thread.id %>_div").html(
  "<%= escape_javascript(
    render partial: 'commontator/threads/show',
           formats: [:html],
           locals: { thread: thread,
                        user: user,
                        page: page,
                        per_page: per_page,
                        show_all: show_all }) %>");

app/views/commontator/threads/show.js.erb
<%= render partial: 'show',
           locals: { thread: @thread,
                        user: @user,
                        page: @commontator_page,
                        per_page: @commontator_per_page,
                        show_all: @show_all } %>

<%= javascript_proc %>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.user_id %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @course.user.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Demo App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Posts', '#' %></li>
                <% if current_user %>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOOC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.content %></td>
        <td><%= lecture.course_id %></td>
        
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>Add New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>
<strong>Course:</strong>
<%= @lecture.course.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @lecture.content.html_safe %>
</p>



<p>
  <strong>Attachment:</strong>
 <%= link_to "Download Attachment", @lecture.attachment_url if @lecture.attachment?  %>
</p>

  <p><%= link_to 'Spam', spam_lecture_path(@lecture), method: :post %></p>

<%= link_to like_lecture_path(@lecture), method: :put do %>
  Like
  <%= @lecture.get_upvotes.size %>
<% end %>

<%= link_to dislike_lecture_path(@lecture), method: :put do %>
  DisLike
  <%= @lecture.get_downvotes.size %>
<% end %>
<br>
<p>
<%= commontator_thread(@lecture) %>
</p>
<br>
<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>